const chinese = {
    view: '查看',
    edit: '编辑',
    viewRental: '查看房租',
    editRental: '编辑房租',
    floor: '楼',
    waterL: '上月水行度：',
    waterT: '本月水行度：',
    waterUse: '实际用水：',
    electricL: '上月电行度：',
    electricT: '本月电行度：',
    electricUse: '实际用电：',
    water: '水费：',
    electric: '电费：',
    net: '网费：',
    house: '租金：',
    manage: '卫生/管理费：',
    total: '总计：',
    editSingle: '编辑单价',
    editByRental: '编辑租金',
    editByWater: '编辑水费',
    editByElectric: '编辑电费',
    editByNet: '编辑网费',
    unit: {
        water: '水费（元/吨）：',
        electric: '电费（元/度）：',
        net: '网费（元/月）：',
        manage: '卫生/管理费（元/月）：',
    },
    flat: '房号',
    lastMonth: '上月',
    thisMonth: '本月',
};

export default chinese;
