export const EDIT_DEFAULT = 'EDIT_DEFAULT';

export const EDIT_SINGLE_WATER = 'EDIT_SINGLE_WATER';
export const EDIT_SINGLE_POWER = 'EDIT_SINGLE_POWER';
export const EDIT_SINGLE_NET = 'EDIT_SINGLE_NET';
export const EDIT_SINGLE_MANAGE = 'EDIT_SINGLE_MANAGE';

export const EDIT_RENTAL = 'EDIT_RENTAL';
export const EDIT_WATER = 'EDIT_WATER';
export const EDIT_POWER = 'EDIT_POWER';
