export const EDIT_DEFAULT = 'EDIT_DEFAULT';

export const EDIT_SINGLE_WATER = 'EDIT_SINGLE_WATER';
export const EDIT_SINGLE_POWER = 'EDIT_SINGLE_POWER';
export const EDIT_SINGLE_NET = 'EDIT_SINGLE_NET';
export const EDIT_SINGLE_MANAGE = 'EDIT_SINGLE_MANAGE';

export const EDIT_RENTAL_RENTED = 'EDIT_RENTAL_RENTED';
export const EDIT_RENTAL_WATERL = 'EDIT_RENTAL_WATERL';
export const EDIT_RENTAL_WATERT = 'EDIT_RENTAL_WATERT';
export const EDIT_RENTAL_WATERUSE = 'EDIT_RENTAL_WATERUSE';
export const EDIT_RENTAL_WATER = 'EDIT_RENTAL_WATER';
export const EDIT_RENTAL_POWERL = 'EDIT_RENTAL_POWERL';
export const EDIT_RENTAL_POWERT = 'EDIT_RENTAL_POWERT';
export const EDIT_RENTAL_POWERUSE = 'EDIT_RENTAL_POWERUSE';
export const EDIT_RENTAL_POWER = 'EDIT_RENTAL_POWER';
export const EDIT_RENTAL_HOUSE = 'EDIT_RENTAL_HOUSE';
export const EDIT_RENTAL_MANAGE = 'EDIT_RENTAL_MANAGE';
export const EDIT_RENTAL_NET = 'EDIT_RENTAL_NET';
